nyc_metro_tracker/nyc_metro_tracker/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from nyc_metro_tracker import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('auth/', include('userauth.urls')),
    path('', include('service_status.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

nyc_metro_tracker/service_status/urls.py
from django.urls import path

from service_status import views

urlpatterns = [
    path('', views.ServiceList.as_view(), name='index'),
    path('details/<int:pk>', views.ServiceDetails.as_view(), name='details'),
    path('favorites/', views.FavoriteServiceList.as_view(), name='favorites')
]

nyc_metro_tracker/userauth/urls.py
from django.urls import path

from userauth import views

urlpatterns = [
    path('create/', views.CreateUser.as_view(), name='create-user'),
    path('create-profile/<int:user_id>/', views.create_profile, name='create-profile'),
    path('add-favorite/<int:service_id>/', views.favorite_service, name='favorite-service'),
    path('remove-favorite/<int:service_id>/', views.unfavorite_service, name='unfavorite-service')
]

nyc_metro_tracker/service_status/models.py
from django.db import models


SERVICE_TYPES = (
    ('subway', 'Subway'),
    ('bus', 'Bus'),
    ('BT', 'Bridge/Tunnel'),
    ('LIRR', 'Long Island Railroad'),
    ('MetroNorth', 'Metro-North Railroad')
)


class Service(models.Model):
    service_type = models.CharField(choices=SERVICE_TYPES, max_length=32)
    name = models.CharField(unique=True, max_length=32)
    status = models.CharField(max_length=32, blank=True)
    text = models.TextField(blank=True)
    datetime = models.DateTimeField(blank=True, null=True)

nyc_metro_tracker/userauth/models.py
from django.contrib.auth.models import User
from django.db import models

from service_status.models import Service


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    favorites = models.ManyToManyField(Service)

nyc_metro_tracker/service_status/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from service_status.models import Service


class ServiceList(ListView):
    model = Service
    template_name = 'service_status/list.html'

    def get_queryset(self):
        filter_val = self.request.GET.get('filter', '')
        if filter_val:
            qs = Service.objects.filter(service_type=filter_val)
        else:
            qs = Service.objects.all()
        return qs


class ServiceDetails(DetailView):
    model = Service
    template_name = 'service_status/details.html'


class FavoriteServiceList(LoginRequiredMixin, ListView):
    model = Service
    template_name = 'service_status/list.html'

    def get_queryset(self):
        user = self.request.user
        queryset = user.profile.favorites.all()
        return queryset

nyc_metro_tracker/userauth/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.views.generic import CreateView

from service_status.models import Service
from userauth.models import Profile


class CreateUser(CreateView):
    model = User
    fields = ['first_name', 'last_name', 'username', 'email', 'password']
    template_name = 'auth/create.html'

    def check_logged_in(self):
        return self.request.user.is_authenticated()

    def get_success_url(self):
        return reverse('create-profile', user_id=self.object.pk)

    def get(self, request, *args, **kwargs):
        if self.check_logged_in():
            raise PermissionDenied()
        return super().get(self, request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        if self.check_logged_in():
            raise PermissionDenied()
        return super().post(self, request, *args, **kwargs)


def create_profile(request, user_id):
    profile = Profile.objects.get_or_create(user=get_object_or_404(User, pk=user_id))
    profile[0].save()
    return redirect('/')


@login_required(login_url='login')
def favorite_service(request, service_id):
    profile = request.user.profile
    service = get_object_or_404(Service, pk=service_id)
    profile.favorites.add(service)
    return redirect('/')


@login_required(login_url='login')
def unfavorite_service(request, service_id):
    profile = request.user.profile
    service = get_object_or_404(Service, pk=service_id)
    profile.favorites.remove(service)
    return redirect('/')

nyc_metro_tracker/service_status/templates/service_status/details.html
{% extends 'base.html' %}

{% block page_title %}{{ object.name }} Details{% endblock %}

{% block content %}
    <h1>Details for {{ object.get_service_type_display }} {{ object.name }}</h1>
    <hr>
    <p><strong>Service Type: </strong>{{ object.get_service_type_display }}</p>
    <p><strong>Name: </strong>{{ object.name }}</p>
    <p><strong>Status: </strong>{{ object.status }}</p>
    {% if object.text %}
        <p><strong>Text: </strong>{{ object.text | linebreaks }}</p>
    {% else %}
        <p><strong>Text: </strong>N/A</p>
    {% endif %}
    {% if object.datetime %}
        <p><strong>Datetime: </strong>{{ object.datetime }}</p>
    {% else %}
        <p><strong>Datetime: </strong>N/A</p>
    {% endif %}
{% endblock %}

nyc_metro_tracker/service_status/templates/service_status/list.html
{% extends 'base.html' %}

{% block page_title %}Service Status{% endblock %}

{% block content %}
    <h1>Service Status</h1>
    <form method="get" action="{% url 'index' %}">
        <div class="row">
        <div class="col"></div>
        <select id="filter-service-type" name="filter" class="form-control mb-2 mx-4 col">
            <option value="">Show All</option>
            <option value="subway">Subway</option>
            <option value="bus">Bus</option>
            <option value="BT">Bridge/Tunnel</option>
            <option value="LIRR">Long Island Railroad</option>
            <option value="MetroNorth">Metro-North Railroad</option>
        </select>
        <button type="submit" class="btn btn-primary mb-2 mx-4 col">Submit</button>
        <div class="col"></div>
        </div>
    </form>
    <table class="table">
        <thead class="thead-light">
            <tr>
                <th scope="col">Type</th>
                <th scope="col">Name</th>
                <th scope="col">Status</th>
                <th scope="col">Details</th>
                <th scope="col">Datetime</th>
                <th scope="col">Favorite</th>
            </tr>
        </thead>
        <tbody>
            {% for service in service_list %}
                <tr>
                    <td>{{ service.get_service_type_display }}</td>
                    <td><a href="{% url 'details' service.id %}">{{ service.name }}</a></td>
                    <td>{{ service.status }}</td>
                    {% if service.text %}
                        <td>{{ service.text | linebreaks }}</td>
                    {% else %}
                        <td>N/A</td>
                    {% endif %}
                    {% if service.datetime %}
                        <td>{{ service.datetime }}</td>
                    {% else %}
                        <td>N/A</td>
                    {% endif %}
                    {% if service in request.user.profile.favorites.all %}
                        <td><a href="{% url 'unfavorite-service' service.id %}">Unfavorite</a></td>
                    {% else %}
                        <td><a href="{% url 'favorite-service' service.id %}">Favorite</a></td>
                    {% endif %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

nyc_metro_tracker/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block page_title %}{% endblock %}</title>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="Ian H. Pittwood">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <script defer src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script defer src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body style="padding-top: 60px">
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <a class="navbar-brand" href="{% url 'index' %}">MTA Service Status</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon">Toggle navigation</span>
    </button>
    <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Status List</a>
            </li>
            {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'favorites' %}">My Favorites</a>
                </li>
            {% endif %}
            {% if request.user.is_authenticated and request.user.is_staff %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                </li>
            {% endif %}
        </ul>
        <ul class="navbar-nav navbar-right">
            {% if not request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Create Account</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>
<main role="main" class="container">
    {% block content %}{% endblock %}
</main>
</body>
</html>